name: release

on:
  push:
    tags:
      - '*'

jobs:
  deploy_release:
    name: deploy_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build_artifact
        run: |
          mv sshbm.sh sshbm
          tar -czvf sshbm.linux.tar.gz sshbm
      - name: check_version
        run: echo "cat version.txt"
        id: version
      - name: create_release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.check_version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
      - name: upload_artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: sshbm.linux.tar.gz
          asset_name: sshbm.linux.tar.gz
          asset_content_type: application/gzip